### ISSUE TITLE
4.md 章节里面的翻译都是机翻，不需要翻译

### ISSUE THREAD

**Issue by cdmikechen** [apachecn/airflow-doc-zh#2]
https://github.com/apachecn/airflow-doc-zh/blob/master/zh/4.md
里面内容都是机翻，实际上直接显示原文内容就可以了。而且没有编排，显示混乱

**Comment by wizardforcel** [comment]
但是需要校对啊。

**Comment by cdmikechen** [comment]
@wizardforcel 后来我看了。。是需要校对的，最开始没注意到，抱歉。我原来写过一些相关的文档翻译，最近我有时间可以把相关的内容补完进去，也当做是帮忙了。
