### ISSUE TITLE
这个是机器翻译的还是人工翻译的?

### ISSUE THREAD

**Issue by zhongjiajie** [apachecn/airflow-doc-zh#38]
维护者你好,我是Airflow的使用者,我想问一下这个repo是机器翻译的还是人工翻译的,因为我看到 https://github.com/apachecn/airflow-doc-zh/issues/2 里面讨论的是机器翻译的.

我没有参加过翻译工作,但是做为airflow的使用者,想要完善中文文档,让更多的人使用airflow.

**Comment by jiangzhonglian** [comment]
都可以，我们在机器翻译的基础上做一些优化，保证文章的可读性，这是一个迭代的过程，别怕翻译错了，大胆地去干，这就是我们坚信的开源世界
