### ISSUE TITLE
建议合并PR的时候使用squash and merge

### ISSUE THREAD

**Issue by zhongjiajie** [apachecn/airflow-doc-zh#40]
刚刚fetch了一些master分支,发现有merge 信息,
![merge-info](http://ww1.sinaimg.cn/large/775a67e7gy1g0gihsc453j20rh04ngm4.jpg)
建议使用squash and merge,使得git历史尽量简单
![squash-and-merge](http://ww1.sinaimg.cn/large/775a67e7gy1g0gieplaxxj20ff08ft9g.jpg)

不知各位维护者意下如何?

**Comment by wizardforcel** [comment]
这个随意吧，取决于负责人的习惯。
