### ISSUE TITLE
为我们的翻译确定的一个基础的版本

### ISSUE THREAD

**Issue by zhongjiajie** [apachecn/airflow-doc-zh#49]
各位好,我在想我们是不是应该为我们翻译确定一个都应的英文原版.好比我和@tssujt 基于这个commit的讨论
https://github.com/apachecn/airflow-doc-zh/commit/a12576d78bb202d0033cc4ca658f9f81667d072d#r32544838

一个是release了的文档,一个是dev中的文档,两个都没有错但是翻译时会存在冲突.
我的建议是我们先以一个版本为基础,如1.10.2,先翻译成中文,然后发布翻译的时候根据版本的浏览不同的网页
* 当我们要访问指定版本的时候使用 `https://airflow.apachecn.org/1.10.2/`
* 当我们要访问最新版的时候使用 `https://airflow.apachecn.org/latest/`

而我们的master分支和Airflow master分支的英文文档保持一致,这样只要Airflow发布最新英文文档的同时我们也能发布最新的中文翻译了.

不知道各位的意见怎么样

**Comment by wizardforcel** [comment]
官网上一直是 1.10.2，没有找到 latest 和 stable 的区分。可能它改动了但没有更新版本号，也可能 1.10.2 就是 latest 版本，但是没写出来。

我们一向不翻译 latest 版本，而是等到它稳定了，有了某个版本号了再翻译。

**Comment by tssujt** [comment]
就翻译1.10.2的吧

**Comment by zhongjiajie** [comment]
@tssujt 好的
