### ISSUE TITLE
文档不像原版文档有搜索功能

### ISSUE THREAD

**Issue by morefreeze** [apachecn/airflow-doc-zh#51]
是否可以把文档放在 https://readthedocs.org/ 上，这样自带的有版本和搜索功能，现在的中文文档这两个都没有 :<

**Comment by morefreeze** [comment]
https://airflow-doc-zh.readthedocs.io/zh_CN/latest/
一个原型，先在我的repo下试验

**Comment by wizardforcel** [comment]
fixed
