### ISSUE TITLE
原版的引用代码在中文里一团乱

### ISSUE THREAD

**Issue by morefreeze** [apachecn/airflow-doc-zh#55]
尝试翻译[28章](https://github.com/morefreeze/airflow-doc-zh/blob/28/zh/28.md)，但生成的中文一团乱，主要是原文直接引用代码，md没有对应的格式，我们这里怎么办？抓下html代码，参数说明可以替换成中文吗？

看了其他的章节，除了API那章，都没有类似的例子可供参考
@wizardforcel @tssujt

**Comment by wizardforcel** [comment]
好了，整理完毕~

**Comment by morefreeze** [comment]
![image](https://user-images.githubusercontent.com/1477233/54867747-cbcf5b80-4dbe-11e9-8e52-056464e08e1b.png)

![image](https://user-images.githubusercontent.com/1477233/54867736-b3f7d780-4dbe-11e9-940b-01d3286a0f74.png)

对比下现在译版和原版，主要有2个地方我不确定要怎么用md来表现，1用反引号会出现滚动条感觉没什么必要，但inline code和 quote的形式都有换行，决定一下吧
`class airflow.contrib.sensors.wasb_sensor.WasbBlobSensor(container_name, blob_name, wasb_conn_id='wasb_default', check_options=None, *args, **kwargs) `
> class airflow.contrib.sensors.wasb_sensor.WasbBlobSensor(container_name, blob_name, wasb_conn_id='wasb_default', check_options=None, *args, **kwargs) 

2 是函数签名，这里感觉用quote的形式会好点
> poke(context)
