### ISSUE TITLE
可以不使用ID作为文件名吗？

### ISSUE THREAD

**Issue by tssujt** [apachecn/airflow-doc-zh#59]
@wizardforcel 

如果想要增加文件的话，好像挺麻烦的

**Comment by zhongjiajie** [comment]
我认为最好是使用官网对应的英文名作为文件名，比较好对应

**Comment by wizardforcel** [comment]
我想改但是没时间改，如果谁有空的话帮忙改一下。

别忘了 SUMMARY 里面也要改。

**Comment by zhongjiajie** [comment]
我举手,可以么? @wizardforcel @tssujt
